### ISSUE TITLE
Utiliser un langage markup plus puissant

### ISSUE THREAD

**Issue by slivering** [ai-safety-saclay/site#7]
TL;DR : il faudrait utiliser Pandoc et/ou Asciidoc à la place de Markdown.

## Le problème

Jusqu'à présent, Markdown fonctionnait bien pour écrire des pages du site. Cependant, il atteint rapidement ses limites pour effectuer des tâches plus compliquées. Il faut alors utiliser du HTML dans le Markdown et ajouter des classes Bootstrap aux éléments, ce qui mélange le contenu et la présentation. En particulier pour les éléments suivants :

### Moins lisible

- Anchors (par exemple, `<h2 id="heading-1">`)
- Images
- Vidéos
- Boutons

### Très contraignant

- Cartes Bootstrap
- Carousels
- Barre de navigation

Point le plus embêtant : par défaut, Markdown ne permet ni **d'inclure du contenu partiel**, ni d'utiliser des **templates**.

## Solutions

Pour une solution viable à long-terme, il faut utiliser un outil markup plus puissant que Markdown.

### Asciidoc

Asciidoc est un langage plus puissant que Markdown avec des fonctionnalités proches de HTML, tout en restant lisible.

**Fonctionnalités générales** :
- [insérer du HTML](https://docs.asciidoctor.org/asciidoc/latest/pass/)
- [générer du HTML](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/)
- facilement [extensible](https://docs.asciidoctor.org/asciidoctor/latest/extensions/)
- créer des des templates : [exemple](https://docs.asciidoctor.org/asciidoctor/latest/extensions/block-macro-processor/)
- [inclure des fichiers Asciidoc ou d'un format différent](https://docs.asciidoctor.org/asciidoc/latest/directives/include/)
- [inclure des fichiers externes](https://docs.asciidoctor.org/asciidoctor/latest/extensions/include-processor/)

**Utilités** :
- [HTML header](https://docs.asciidoctor.org/asciidoc/latest/document/header/)
- [insertion d'image](https://docs.asciidoctor.org/asciidoc/latest/macros/images/) avec beaucoup de fonctionnalités
- [YouTube embed](https://docs.asciidoctor.org/asciidoc/latest/macros/audio-and-video/#vimeo-and-youtube-videos)
- [lead text](https://docs.asciidoctor.org/asciidoc/latest/blocks/preamble-and-lead/)
- [génération automatique ou manuelle d'identifiants de section (anchors)](https://docs.asciidoctor.org/asciidoc/latest/sections/auto-ids/)

### Pandoc

[Pandoc](https://pandoc.org/getting-started.html) est une sorte de convertisseur universel entre les formats markup. Il permet notamment de manipuler des [templates](https://pandoc.org/MANUAL.html#templates) et des [fichiers partiels](https://pandoc.org/chunkedhtml-demo/6.1-template-syntax.html#partials).

Le [format Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown) accepté par Pandoc comporte de nombreuses extensions :
- [identifiants de section](https://pandoc.org/MANUAL.html#heading-identifiers)
- [Markdown dans HTML](https://pandoc.org/MANUAL.html#extension-markdown_in_html_blocks)
- [Images](https://pandoc.org/MANUAL.html#images)
- etc.

#### Désavantages

- C'est comme `ffmpeg` : beaucoup de dépendances à installer
- Pandoc n'est pas incompatible avec Asciidoc, mais la conversion `Asciidoc > HTML` [nécessite de passer par d'autres outils](https://github.com/jgm/pandoc/issues/1456).

### Autres

- [rST](http://docutils.sourceforge.net/docs/ref/rst/introduction.html)
- [OrgMode](http://orgmode.org/)

**Comment by rambip** [comment]
J'étais motivé pour passer à asciidoc mais l'implementation python est moche et il n'y a aucune API qui permet de convertir le fichier en chaine de caracteres directement.

J'ai activé l'extension "md in html" qui permet de mettre n'import quel contenu md dans un conteneur html, c'est déjà ça (voir [ici](https://python-markdown.github.io/extensions/md_in_html/) )

**Comment by slivering** [comment]
> J'étais motivé pour passer à asciidoc mais l'implementation python est moche et il n'y a aucune API qui permet de convertir le fichier en chaine de caracteres directement.

Il semble que l'outil principal est Asciidoctor, qui est écrit en Ruby. On dispose quand même de [asciidoc3](https://asciidoc3.org/quickstart.html), une implémentation en Python 3 (mise à jour récemment) installable via pip.

S'il faut récupérer le HTML sous forme de `str`, c'est effectivement très moche :

`test.txt`
```asciidoc
Hello *{author}*
```
```python
from asciidoc3 import asciidoc3
from asciidoc3.asciidoc3api import AsciiDoc3API
import io

def asciidoc_to_html(file_path: str, **variables) -> str:
    with open(file_path, 'r') as f:
        content = f.read()
    infile = io.StringIO(content)
    outfile = io.StringIO()
    api = AsciiDoc3API(asciidoc3.__file__)
    api.options('--no-header-footer')
    api.attributes = variables
    api.execute(infile, outfile, backend='html5')
    return outfile.getvalue()

print(asciidoc_to_html('test.txt', author='PIAF'))
```

Résultat :
```
<unknown>:1: SyntaxWarning: invalid escape sequence '\S'
<unknown>:1: SyntaxWarning: invalid escape sequence '\S'
<div class="paragraph"><p>Hello <strong>PIAF</strong></p></div>
```

Par ailleurs, le fait que Asciidoc permette d'inclure des fichiers partiels (Asciidoc, HTML) réduit déjà le nombre d'invocations du programme.

Je pense qu'utiliser `asciidoc3` en vaut quand même le coup.

**Comment by rambip** [comment]
Sinon on peut aussi faire ça: https://pypi.org/project/jinja-markdown/

C'est pas super beau mais ça pourrait nous suffire.

**Comment by rambip** [comment]
À priori ça va résoudre beaucoup de problèmes: tout est défini avec la syntaxe html par défaut, on peut utiliser des templates là où on a besoin. Il y a une bonne documentation et l'outil a été fait pour python.

Quand on aura besoin de contenu markdown, on pourra directement l'écrire dans le template. 

Autre avantage: ça sera beaucoup plus simple d'intégrer le blog ensuite.

Je m'en occupe dès que possible.

**Comment by rambip** [comment]
C'est fait, il ne reste plus qu'à intégrer le blog à tout ça.

Je pense que l'outil que j'avais proposé pour le blog est overkill, un outil comme [celui ci](https://pypi.org/project/mdtex2html/) pourrait suffire.
